// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartShelf_context_index from "./islands/AddToCartShelf/context/index.tsx";
import * as $AddToCartShelf_context_types from "./islands/AddToCartShelf/context/types.ts";
import * as $AddToCartShelf_index from "./islands/AddToCartShelf/index.tsx";
import * as $KitLook from "./islands/KitLook.tsx";
import * as $functions_headerFunctions from "./islands/functions/headerFunctions.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartShelf/context/index.tsx": $AddToCartShelf_context_index,
    "./islands/AddToCartShelf/context/types.ts": $AddToCartShelf_context_types,
    "./islands/AddToCartShelf/index.tsx": $AddToCartShelf_index,
    "./islands/KitLook.tsx": $KitLook,
    "./islands/functions/headerFunctions.tsx": $functions_headerFunctions,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
